# Generated by Django 3.1.4 on 2021-04-29 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='freshprice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='saltyprice',
        ),
    ]
